# Generated by Django 5.1 on 2025-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_coin_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['-id'], 'verbose_name': 'Coin', 'verbose_name_plural': 'Coins'},
        ),
        migrations.AddField(
            model_name='coin',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='multioffer',
            name='status',
            field=models.CharField(choices=[('с', 'under consideration'), ('a', 'accepted'), ('d', 'done')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('с', 'under consideration'), ('a', 'accepted'), ('d', 'done')], default='c', max_length=1),
        ),
    ]
