# Generated by Django 5.1 on 2025-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_alter_coin_options_coin_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for coin verification shipment', max_length=50, null=True),
        ),
    ]
