# Generated by Django 5.1 on 2025-03-30 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_coin_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year_from', models.IntegerField(blank=True, help_text='Рік початку діапазону', null=True)),
                ('year_to', models.IntegerField(blank=True, help_text='Рік кінця діапазону', null=True)),
                ('interested_materials', models.CharField(blank=True, choices=[('gold', 'au'), ('silver', 'ag'), ('platinum', 'pt'), ('palladium', 'pd'), ('copper', 'cu'), ('nickel', 'ni'), ('zinc', 'zn'), ('tin', 'sn'), ('bronze', 'bronze'), ('brass', 'brass'), ('cupronickel', 'cupronickel'), ('aluminum', 'al'), ('iron', 'fe'), ('lead', 'pb'), ('magnesium', 'mg'), ('magnetic metals', 'magnetic metals'), ('titanium', 'ti')], help_text='Матеріали монет', max_length=200)),
                ('additional_notes', models.TextField(blank=True, help_text='Додаткові примітки')),
                ('interested_continents', models.ManyToManyField(blank=True, related_name='interested_users', to='coins.continent')),
                ('interested_countries', models.ManyToManyField(blank=True, related_name='interested_users', to='coins.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Опитування користувача',
                'verbose_name_plural': 'Опитування користувачів',
                'ordering': ['-created'],
            },
        ),
    ]
