# Generated by Django 5.1 on 2025-04-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_usersurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='sent_for_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('n', 'not active'), ('e', 'exchanged'), ('v', 'sent for verification'), ('w', 'wait for delivery'), ('s', 'sent')], default='a', max_length=1),
        ),
    ]
