# Generated by Django 5.1 on 2025-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_coin_sent_for_verification_date_alter_coin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
