# Generated by Django 5.1 on 2025-05-30 21:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0009_coin_description_coin_text_coin_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
