# Generated by Django 5.1 on 2025-05-30 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0010_continent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='text',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='text',
        ),
        migrations.RemoveField(
            model_name='country',
            name='text',
        ),
        migrations.AddField(
            model_name='coin',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
