# Generated by Django 5.1 on 2025-05-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_pageseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageseo',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
