# Generated by Django 5.1 on 2025-05-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0013_pageseo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('head', 'Inside <head>'), ('body_top', 'Top of <body>'), ('body_bottom', 'Bottom of <body>')], default='head', max_length=20)),
                ('content', models.TextField(help_text='Insert full <script>...</script> or inline JS')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
