# Generated by Django 5.1 on 2025-06-12 22:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_globalscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('continents', models.ManyToManyField(blank=True, related_name='coin_categories', to='coins.continent')),
                ('countries', models.ManyToManyField(blank=True, related_name='coin_categories', to='coins.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='coins.coincategory')),
            ],
            options={
                'verbose_name': 'Категорія монет',
                'verbose_name_plural': 'Категорії монет',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coins', to='coins.coincategory'),
        ),
    ]
