# Generated by Django 5.1 on 2025-06-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0015_coincategory_coin_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='category',
        ),
        migrations.AddField(
            model_name='coin',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='coins', to='coins.coincategory'),
        ),
    ]
