# Generated by Django 5.1 on 2025-06-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_remove_coin_category_coin_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincategory',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
