# Generated by Django 5.1 on 2025-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0017_coincategory_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва значка')),
                ('description', models.TextField(verbose_name='Опис значка')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Іконка значка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Значок',
                'verbose_name_plural': 'Значки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='users', to='coins.badge', verbose_name='Значки'),
        ),
    ]
