# Generated by Django 5.1 on 2025-07-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0018_badge_userprofile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='legendary',
            field=models.BooleanField(default=False, verbose_name='Легендарний'),
        ),
    ]
