# Generated by Django 5.1 on 2025-07-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0019_badge_legendary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coincategory',
            options={'ordering': ['ordering'], 'verbose_name': 'Категорія монет', 'verbose_name_plural': 'Категорії монет'},
        ),
        migrations.AddField(
            model_name='coincategory',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
