# Generated by Django 5.1 on 2025-07-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0020_alter_coincategory_options_coincategory_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
