# Generated by Django 5.1 on 2025-12-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0022_topic_typeobject_coin_name_coin_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincategory',
            name='type_objects',
            field=models.ManyToManyField(blank=True, related_name='coin_categories', to='coins.typeobject'),
        ),
    ]
